<!DOCTYPE html>
<html>
<head>
  <title>Throne Room LA</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
    }

    header {
      background-color: #333;
      color: #fff;
      padding: 20px;
      text-align: center;
    }

    nav {
      background-color: #555;
      color: #fff;
      padding: 10px;
      text-align: center;
    }

    nav a {
      color: #fff;
      text-decoration: none;
      margin: 0 10px;
    }

    main {
      padding: 20px;
    }

    footer {
      background-color: #333;
      color: #fff;
      padding: 20px;
      text-align: center;
    }
  </style>
</head>
<body>
  <header>
    <h1>Welcome to Throne Room LA</h1>
  </header>

  <nav>
    <a href="#home">Home</a>
    <a href="#about">About Us</a>
    <a href="#services">Services</a>
    <a href="#ministries">Ministries</a>
    <a href="#events">Events</a>
    <a href="#sermons">Sermons</a>
    <a href="#contact">Contact</a>
  </nav>

  <main>
    <section id="home">
      <h2>Welcome to Throne Room LA</h2>
      <p>Experience the presence of God in our worship services.</p>
    </section>

    <section id="about">
      <h2>About Us</h2>
      <p>Learn about the history, values, and beliefs of our church.</p>
    </section>

    <section id="services">
      <h2>Services</h2>
      <p>Join us for worship services:</p>
      <ul>
        <li>Sunday: 10:00 AM</li>
        <li>Wednesday: 7:00 PM</li>
      </ul>
    </section>

    <section id="ministries">
      <h2>Ministries</h2>
      <p>Discover our ministries:</p>
      <ul>
        <li>Youth Ministry</li>
        <li>Women's Ministry</li>
        <li>Men's Ministry</li>
        <li>Outreach Programs</li>
      </ul>
    </section>

    <section id="events">
      <h2>Events</h2>
      <p>Upcoming events:</p>
      <ul>
        <li>April 15: Community Outreach</li>
        <li>April 22: Worship Night</li>
      </ul>
    </section>

    <section id="sermons">
      <h2>Sermons</h2>
      <p>Listen to our latest sermons:</p>
      <ul>
        <li><a href="#">Sermon 1</a></li>
        <li><a href="#">Sermon 2</a></li>
      </ul>
    </section>

    <section id="contact">
      <h2>Contact</h2>
      <p>Get in touch with us:</p>
      <p>123 Church Street, Los Angeles, CA 90001</p>
      <p>Phone: (123) 456-7890</p>
      <p>Email: info@throneroomla.com</p>
    </section>
  </main>

  <footer>
    <p>&copy; 2024 Throne Room LA. All rights reserved.</p>
  </footer>
</body>
</html>
